import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 >
          Welcome to The Jira Metics Hub (JMH)
        </h1>


          <Link href="/DailyMetrics/156"><a>Current Sprint</a></Link><br/>
          <Link href={`/Epics/${encodeURIComponent("Epic Name ~ \"Archi*\"")}`}><a>Arch Epics</a></Link><br/>
          <Link href="/BasicSummary/156"><a>Basic Summary</a></Link><br/>
          
      </main>

      <footer >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span >
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
